server:
  port: 1111

# jpa
spring:
  datasource:
    url: jdbc:sqlserver://183.100.213.43:9011;databaseName=BASE_QMS_GS;encrypt=false
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: enssel!@#$
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl